# docker image
image: getterminus/angular-ci-images:node14

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - dependencies
  # - test
  - build
  - deploy

npm:
  stage: dependencies
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
      - cp ./src/environments/environment.staging.ts  ./src/environments/environment.ts 
      - cp karma.staging.conf.js  karma.conf.js
      - apt-get install git
      - npm install
      - npm link @angular/cli@9.1.15
      - npm test
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/

# jasmine:
#   stage: test
  
#   dependencies:
#     - npm
#   script:
#     - cp ./src/environments/environment.staging.ts  ./src/environments/environment.ts 
#     - cp karma.staging.conf.js  karma.conf.js
#     - npm link @angular/cli@9.1.15
#     - npm test --watch=false

staging_build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - dist/
  script:
    - cp ./src/environments/environment.staging.ts  ./src/environments/environment.ts 
    - npm link @angular/cli@11.2.6
    - npm run build
  dependencies:
    - npm
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - dist/

production_build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - dist/
  script:
    - npm link @angular/cli@11.2.6
    - npm build --prod
  dependencies:
    - npm
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - dist/


staging:
  stage: deploy
  script:
    - *init_ssh
    - sudo apt-get install -y zip
    - cd ./dist && zip -r ./app.zip .
    - scp ./app.zip root@104.207.144.7:/var/www/staging-system.novicompu.com/
    - ssh root@104.207.144.7 'rm -R /var/www/staging-system.novicompu.com/public/* && unzip -o /var/www/staging-system.novicompu.com/app.zip -d /var/www/staging-system.novicompu.com/public/'
  only:
    - master
  dependencies:
    - staging_build
  

production:
  stage: deploy
  script:
    - *init_ssh
    - sudo apt-get install -y zip
    - cd ./dist && zip -r ./app.zip .
    - scp ./app.zip root@104.207.144.7:/var/www/system.novicompu.com/
    - ssh root@104.207.144.7 'rm -R /var/www/system.novicompu.com/public/* && unzip -o /var/www/system.novicompu.com/app.zip -d /var/www/system.novicompu.com/public/'
  when: manual
  only:
    - master
  dependencies:
    - production_build