# docker image
image: getterminus/angular-ci-images:node14

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - dependencies
  - test
  - build
  - deploy

npm:
  stage: dependencies
  cache:
    paths:
      - node_modules/
  script:
      - cp ./src/environments/environment.staging.ts  ./src/environments/environment.ts 
      - apt-get install git
      - npm install
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - ./src/environments/environment.ts 

jasmine:
  stage: test
  cache:
    paths:
      - node_modules/
  dependencies:
    - npm
  script:
    - cp karma.staging.conf.js  karma.conf.js
    - npm i -g @angular/cli@9.1.15
    - npm test

# staging_build:
#   stage: build
#   cache:
#     paths:
#       - dist/
#   script:
    
#     - npm
#   artifacts:
#     expire_in: 1 month
#     paths:
#       - node_modules/
#       - dist/

#   only:
#     - master

# production_build:
#   stage: build
#   cache:
#     paths:
#       - dist/
#   script:
    
#   dependencies:
#     - npm
#   artifacts:
#     expire_in: 1 month
#     paths:
#       - node_modules/
#       - dist/
#   only:
#     - master

staging:
  stage: deploy
  script:
    - *init_ssh
    - cp ./src/environments/environment.staging.ts  ./src/environments/environment.ts 
    - npm i -g @angular/cli@11.2.6
    - ng build
    - apt-get update
    - apt-get install -y zip unzip
    - cd ./dist && zip -r ./app.zip .
    - scp ./app.zip root@104.207.144.7:/var/www/staging-system.novicompu.com/
    - ssh root@104.207.144.7 'rm -R /var/www/staging-system.novicompu.com/public/* && unzip -o /var/www/staging-system.novicompu.com/app.zip -d /var/www/staging-system.novicompu.com/public/'
  cache:
    paths:
      - dist/
  only:
    - master

  

production:
  stage: deploy
  script:
    - *init_ssh
    - npm i -g @angular/cli@11.2.6
    - ng build --prod
    - apt-get update
    - apt-get install -y zip unzip
    - cd ./dist && zip -r ./app.zip .
    - scp ./app.zip root@104.207.144.7:/var/www/system.novicompu.com/
    - ssh root@104.207.144.7 'rm -R /var/www/system.novicompu.com/public/* && unzip -o /var/www/system.novicompu.com/app.zip -d /var/www/system.novicompu.com/public/'
  cache:
    paths:
      - dist/
  when: manual
  only:
    - master