# docker image
image: node:16.14.2-bullseye

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stages:
  - dependencies
  - test
  - build
  - deploy

npm:
  stage: dependencies
  cache:
    paths:
      - node_modules/
  script:
      - apt-get update --force-yes
      # - cp ./src/environments/environment.staging.ts  ./src/environments/environment.ts
      - apt-get install git -y
      - npm install
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      # - ./src/environments/environment.ts

# jasmine:
#   stage: test
#   dependencies:
#     - npm
    # before_script:
    #   - apt-get update --force-yes
    #   - apt-get install git -y
    #   - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #   - apt-get install ./google-chrome*.deb -y
    #   - export CHROME_BIN=/usr/bin/google-chrome
    #   - npm install
#   script:
#     - cp karma.staging.conf.js  karma.conf.js
#     - npm i -g @angular/cli
#     - npm run test -- --not-watch --browsers=ChromeHeadlessCI

staging:
  stage: deploy
  cache:
    paths:
      - dist/
  before_script:
    - apt-get update --force-yes
    - apt-get install -y zip unzip

  script:
    - *init_ssh
    # - cp ./src/environments/environment.staging.ts  ./src/environments/environment.ts
    # - npm i -g @angular/cli
    # - ng b --configuration staging
    - npm run "build:staging"
    - cd ./dist && zip -r ./app.zip .
    - scp ./app.zip root@104.207.144.7:/var/www/staging-system.novicompu.com/
    - currentDate=`date '+%F %T'`
    - ssh root@104.207.144.7 "cd /var/www/staging-system.novicompu.com/ && mkdir tmp && unzip -o ./app.zip -d  ./tmp/ && mv ./public ./'$currentDate' && mv ./tmp ./public"
  only:
    - master


production:
  stage: deploy
  cache:
    paths:
      - dist/
  before_script:
    - apt-get update
    - apt-get install -y zip unzip
  script:
    - *init_ssh
    # - npm i -g @angular/cli
    # - ng b --configuration production
    - npm run build
    - cd ./dist && zip -r ./app.zip .
    - scp ./app.zip root@104.207.144.7:/var/www/system.novicompu.com/
    - currentDate=`date '+%F %T'`
    - ssh root@104.207.144.7 "cd /var/www/system.novicompu.com/ && mkdir tmp && unzip -o ./app.zip -d  ./tmp/ && mv ./public ./'$currentDate' && mv ./tmp ./public"
  when: manual
  only:
    - master
