# docker image
image: node:14-alpine

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

npm:
  stage: mount
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
      - apk add --update npm
      - apk add git
      - npm install
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/

jasmine:
  stage: test
  
  dependencies:
    - npm
  script:
    - npm i -g @angular/cli
    - ng test

build: 
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - dist/
  script:
    - npm i -g @angular/cli
    - ng build --prod
   dependencies:
    - npm
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/

staging:
  stage: deploy
  script:
    - *init_ssh
  only:
    - master
  dependencies:
    - build
  



  
# production:
#   stage: deploy
#   script:
#     - *init_ssh
#     - php ./vendor/deployer/deployer/bin/dep deploy prod
#   when: manual
#   only:
#     - master